name: Build
on:
  workflow_call:
    inputs:
      os:
        required: false
        default: ubunut-latest
        type: string

jobs:
  build:
    name: Build ${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven
      - name: Build with Maven
        run: mvn -B package --file pom.xml
      - uses: actions/upload-artifact@v3
        if: always()
        with:
          path: target/*.jar
      - name: Update dependancy graph
        uses: advanced-security/maven-dependency-submission-action@571e99aab1055c2e71a1e2309b9691de18d6b7d6